#!/bin/bash

source ../../.env

mvn spring-boot:run -Dspring-boot.run.arguments=" \
--SPRING_DATASOURCE_URL=$API_SPRING_DATASOURCE_URL \
--SPRING_DATASOURCE_USERNAME=$API_SPRING_DATASOURCE_USERNAME \
--SPRING_DATASOURCE_PASSWORD=$API_SPRING_DATASOURCE_PASSWORD \
--SPRING_JPA_HIBERNATE_DDL_AUTO=$API_SPRING_JPA_HIBERNATE_DDL_AUTO \
--AUTH_WHITELISTED_EMAILS=$API_AUTH_WHITELISTED_EMAILS \
--AWS_ACCESS_KEY=$API_AWS_ACCESS_KEY \
--AWS_SECRET_KEY=$API_AWS_SECRET_KEY \
--AWS_S3_BUCKETS_BLOG=$API_AWS_S3_BUCKETS_BLOG \
--SECURITY_JWT_SECRET_KEY=$API_SECURITY_JWT_SECRET_KEY \
--SECURITY_CORS_ALLOWED_ORIGINS=$API_SECURITY_CORS_ALLOWED_ORIGINS"
