pipeline {
    agent any 

    environment {
        VERSION = '5.0.0'
    }
    
    stages {
        stage('Build & Test') {
            steps {
                sh 'cd web'
                sh 'sudo docker build .'
            }
        }
        
        stage('Deploy') {
            when {
                branch 'prod'
            }

            steps {
                sh 'cd web'
                sh 'sudo docker build . -t michaelyi/personal-website-web:${VERSION}'
                sh 'sudo docker push michaelyi/personal-website-web:${VERSION}'
            }
        }
    }
}