pipeline {
    agent any 

    environment {
        VERSION = '5.0.0'
    }
    
    stages {
        stage('Build & Test') {
            steps {
                dir ('web') {
                    sh 'sudo docker build .'
                }
            }
        }
        
        stage('Deploy') {
            when {
                branch 'prod'
            }

            steps {
                dir ('web') {
                    sh 'sudo docker build . -t michaelyi/personal-website-web:${VERSION}'
                    sh 'sudo docker push michaelyi/personal-website-web:${VERSION}'
                }
            }
        }
    }
}